### PR TITLE
Create awnish.html

### PR DESCRIPTION
**Pull request by awnishmmg**
Hi Salim Bhai Please Review this code and Add in Your Repository

### CODE REVIEW

**Comment by pandeyharsh317** [comment]
sirrrrrrrrrr @awnishmmg ek baar phir se repeat kar dejiye....................................................

**Comment by ankitnishad6313** [comment]
Salem bhai object  me jo sir ne changes kiye hai wo sahi  hai....

**Comment by saxenavijay** [comment]
Saleem bhai Sir ne jo changes kiye hai wo sahi h...aap ise  aage proceed kar dijiye

**Comment by 7388911607** [comment]
salem bhai

**Comment by tiwarigaurav8303** [comment]
Samajh Raha hai vinod

**Review by salemzubair — COMMENTED** [review]
Ye code kya karta hai

**Comment by yadavankitayadav97** [comment]
sir  you can response me   why we use this code here

**Comment by mohd36523** [comment]
یہ کوڈ سرخی کو پرنٹ کرتا ہے۔

**Comment by prashantupadhyay149** [comment]
hello  bhai @

**Comment by prashantupadhyay149** [comment]
hello  bhai @

**Comment by awnishmmg** [comment]
Salim bhai ye heading ko h1 mey dikhayega

**Comment by ShekhAmberAbbas** [comment]
salem bhai code sahi nhi ha check na krna virus ha usme

**Comment by mohd36523** [comment]
**Squash**
In Git, the term squash is used to squash the previous commits into one. It is not a command; instead, it is a keyword. The squash is an excellent technique for ...

**Comment by Anjneya1999** [comment]
> Hi Salim Bhai Please Review this code and Add in Your Repository. . . . . . . . .

**Pull request merged**
